# Generated by Django 2.2 on 2020-04-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user'),
    ]

    operations = [
    ]
