# Generated by Django 2.2 on 2020-04-01 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('problem_id', models.IntegerField()),
                ('result', models.CharField(blank=True, max_length=36)),
                ('memory', models.CharField(blank=True, max_length=36)),
                ('time', models.CharField(blank=True, max_length=36)),
                ('lang', models.CharField(max_length=36)),
                ('length', models.CharField(blank=True, max_length=36)),
                ('submitted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('code', models.TextField()),
            ],
        ),
    ]
