# Generated by Django 2.2 on 2020-04-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time_limit', models.CharField(max_length=36)),
                ('memory_limit', models.CharField(max_length=36)),
                ('point', models.IntegerField()),
                ('description', models.TextField()),
                ('input_format', models.TextField(blank=True)),
                ('output_format', models.TextField(blank=True)),
                ('sample_input', models.TextField(blank=True)),
                ('sample_output', models.TextField(blank=True)),
                ('hint', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
